#' @title Sample noise.matrix object
#'
#' @description
#' This is a sample noise.matrix object generated by the bgNoise function. Used in the examples of: [singleSat] and [activity]
#' <br> The original sound file was obtained from the Escutadô Project, an initiative aimed at recording soundscapes across the Brazilian semiarid region. The audio was recorded by an autonomous recorder (SM4) attached approximately 4'11" inches above ground on a metal rod installed in a Black Jurema (Mimosa tenuiflora) forest in Federal Rural University of the Semi-Arid (UFERSA), located in Mossoró, Rio Grande do Norte, Brazil. The recording was taken at midnight (00:00) and is 3 minutes long, with a sampling rate of 48 kHz and gain levels of 16 dB on the left channel and 10 dB on the right channel.
#'
#' @format ## `sampleBGN`
#' A noise.matrix object with:
#' \describe{
#' \item{@values}{Background Noise and Soundscape Power values}
#' \item{@timeBins}{Duration in seconds of each time bin}
#' \item{@sampRate}{The recording's sample rate}
#' \item{@wl}{The window length used to generate the spectrogram used to calculate the metrics}
#' \item{@channel}{The channel or channels of the recording}
#' }
#'
#' @source <https://zenodo.org/records/17243660>
#'
"sampleBGN"
