# Tell R CMD check that these arguments are imported externally in satBackup
utils::globalVariables(c(
  'soundpath',
  'backup',
  'powthr',
  'bgnthr',
  'wl',
  'timeBin',
  'targetSampRate',
  'overlap',
  'channel',
  'dbThreshold',
  'histbreaks',
  'DCfix',
  'normality',
  'type',
  'od',
  'nFiles',
  'concluded'
))
