# noise.matrix class ------------------------------------------------------

setClass(
  "noise.matrix.generic",
  slots = representation(
    index = "character",
    values = "list",
    timeBins = "numeric",
    sampRate = "numeric",
    channel = "character"
  )
)

#' @title noise.matrix class
#'
#' @description
#' This class object is generated by the [bgNoise] function. It can be read by [soundSat].
#' <br>Methods: [show()] and [plot()][plot,noise.matrix,ANY-method]
#'
#' @slot values a list containing the values of BGN and POW. Indices are separated in individual data.frames by channel
#' @slot timeBins numeric vector containing the duration of each time bin
#' @slot sampRate single numeric string containing the audio's sampling rate
#' @slot wl single numeric string containing the spectrogram's window length
#' @slot channel single character string containing the channel or channels used to calculated the indices
#'
#' @returns
#' A `noise.matrix` object
#'
#' @export
#'
#' @seealso [bgNoise()]
setClass("noise.matrix",
         contains = "noise.matrix.generic",
         slots = representation(wl = "numeric"))

setClass("noise.matrix.internal",
         contains = "noise.matrix.generic",
         slots = representation(path = "character"))

# show --------------------------------------------------------------------

setMethod("show", signature(object = "noise.matrix"), function(object) {
  nBins = length(object@timeBins)
  titleMap = list("BGN+POW" = "Background Noise and Soundscape Power",
                  "ACI" = "Spectral Acoustic Complexity Index",
                  "ENT" = "Spectral Acoustic Entrophy Index")

  cat(titleMap[[paste(object@index, collapse = "+")]])
  cat("\nIndex:                 ", object@index)
  cat("\nChannel:               ", object@channel)
  cat("\nSampling Rate (Hz):    ", object@sampRate)
  cat("\nWindow Length:         ", object@wl)
  cat("\nTemporal Bins:         ", nBins, "\n")

  if (object@channel == "stereo") {
    if (nBins <= 5) {
      powDist = nBins * 10 + 2

      cat("\n@values$left\n")

      out = lapply(object@index, function(ind) {
        capture.output(rbind(head(
          as.data.frame(
            lapply(object@values$left[[ind]], function(col)
              sprintf("%9.5f", col)),
            col.names = paste0("$", ind, 1:nBins),
            check.names = FALSE
          ),
          5
        ), "..."))
      })

      cat(paste0("$", object@index, collapse = strrep(" ", powDist)),
          do.call(paste, c(out, sep = strrep(" ", 5))),
          sep = "\n")

      cat("\n@values$right\n")

      out = lapply(object@index, function(ind) {
        capture.output(rbind(head(
          as.data.frame(
            lapply(object@values$right[[ind]], function(col)
              sprintf("%9.5f", col)),
            col.names = paste0("$", ind, 1:nBins),
            check.names = FALSE
          ),
          5
        ), "..."))
      })

      cat(paste0("$", object@index, collapse = strrep(" ", powDist)),
          do.call(paste, c(out, sep = strrep(" ", 5))),
          sep = "\n")

    } else {
      powDist = 38

      cat("\n@values$left\n")

      out = lapply(object@index, function(ind) {
        capture.output(setNames(cbind(rbind(
          head(as.data.frame(
            lapply(object@values$left[[ind]][, 1:3], function(col)
              sprintf("%9.5f", col)),
            check.names = FALSE
          ), 5), "..."
        ), "..."), paste0("$", ind, c(1:3, "."))))
      })

      cat(paste0("$", object@index, collapse = strrep(" ", powDist)),
          do.call(paste, c(out, sep = strrep(" ", 5))),
          sep = "\n")

      cat("\n@values$right\n")

      out = lapply(object@index, function(ind) {
        capture.output(setNames(cbind(rbind(
          head(as.data.frame(
            lapply(object@values$right[[ind]][, 1:3], function(col)
              sprintf("%9.5f", col)),
            check.names = FALSE
          ), 5), "..."
        ), "..."), paste0("$", ind, c(1:3, "."))))
      })

      cat(paste0("$", object@index, collapse = strrep(" ", powDist)),
          do.call(paste, c(out, sep = strrep(" ", 5))),
          sep = "\n")

    }
  } else {
    rChannel = object@channel

    cat("\n@values$", rChannel, "\n", sep = "")

    if (nBins <= 5) {
      powDist = nBins * 10 + 2

      out = lapply(object@index, function(ind) {
        capture.output(rbind(head(
          as.data.frame(
            lapply(object@values[[rChannel]][[ind]], function(col)
              sprintf("%9.5f", col)),
            col.names = paste0("$", ind, 1:nBins),
            check.names = FALSE
          ),
          5
        ), "..."))
      })

      cat(paste0("$", object@index, collapse = strrep(" ", powDist)),
          do.call(paste, c(out, sep = strrep(" ", 5))),
          sep = "\n")

    } else {
      powDist = 38

      out = lapply(object@index, function(ind) {
        capture.output(setNames(cbind(rbind(
          head(as.data.frame(
            lapply(object@values[[rChannel]][[ind]][, 1:3], function(col)
              sprintf("%9.5f", col)),
            check.names = FALSE
          ), 5), "..."
        ), "..."), paste0("$", ind, c(1:3, "."))))
      })

      cat(paste0("$", object@index, collapse = strrep(" ", powDist)),
          do.call(paste, c(out, sep = strrep(" ", 5))),
          sep = "\n")
    }
  }
})

# plot --------------------------------------------------------------------

#' Plot noise.matrix objects
#'
#' @param x an `noise.matrix` object
#' @param channel channel or channels to be ploted. By default, this set to `x@channel`, but can be changed to `left` or `right` if `x@channel` = `stereo`
#' @param bin temporal bin to be plotted. Defaults to `1`
#' @param index a character vector of length 1 or 2 with indexes to be plotted. Available indices are: `c("BGN", "POW")`, `"BGN"`, `"POW"` and `"ACI"`. Defaults to the indexes listed in `x@index`
#' @param nbreaks amount of breaks of the y axis. Defaults to `5`
#' @param yunit frequency unit to be used in plot. Available units are: `"hz"` and `"khz"`. Defaults to `"hz"`
#' @param main title for the plot. Set two strings if you are plotting and stereo noise.matrix. If set to `NULL`, default title will be `left/right/mono channel`
#' @param xlab label for the x-axis. Changes depending on `x@index`
#' @param ylab label for the y-axis. Defaults to `"Frequency"`
#' @param col plotting color for de indices. Defaults to `c("blue","red")`
#' @param type desired plot type. For details see [base::plot]
#' @param draw0 if a stripped line should be drawn at 0. Defaults to `TRUE`
#' @param box if a box should be drawn around the plot. Defaults to `TRUE`
#' @param axes if axes should be drawn. Defaults to `TRUE`
#' @param annotate if bin information should be added to the plot. Defaults to `TRUE`
#' @param ... further [graphical parameters] passed down to plot
#'
#' @details This is a method to quickly plot the results of [bgNoise]. This calls the helper function `plotBGN`, which is not meant to be used or seen by the user.
#'
#' @importFrom grDevices xy.coords
#' @importFrom graphics abline
#' @importFrom graphics axis
#' @importFrom graphics mtext
#' @importFrom graphics par
#' @importFrom graphics plot.new
#' @importFrom graphics plot.window
#' @importFrom graphics plot.xy
#' @importFrom methods new
#' @importFrom utils head
#'
#' @export
#'
setMethod("plot", signature(x = "noise.matrix"), function(x,
                                                          channel = NULL,
                                                          bin = 1,
                                                          index = NULL,
                                                          nbreaks = 5,
                                                          yunit = c("hz", "khz"),
                                                          main = NULL,
                                                          xlab = NULL,
                                                          ylab = "Frequency",
                                                          col = c("blue", "red"),
                                                          type = "p",
                                                          draw0 = TRUE,
                                                          box = TRUE,
                                                          axes = TRUE,
                                                          annotate = TRUE,
                                                          ...) {
  if (!is.null(channel)) {
    channel = match.arg(channel, c("stereo", "mono", "left", "right"))
  } else {
    channel = x@channel
  }

  if (is.null(main)) {
    main = "channel"
  }

  if (is.null(xlab)) {
    xlab = switch(paste(sort(x@index), collapse = "+"),
                  "BGN+POW" = "dB",
                  "ACI" = "Amplitude",
                  "ENT" = "Entropy")
  }

  yunit = match.arg(yunit)

  if (length(x@timeBins) < bin) {
    bin = length(x@timeBins)
  }

  if (is.null(index)) {
    index = x@index
  }

  plotNOISE(
    x = x,
    channel = channel,
    bin = bin,
    index = index,
    nbreaks = nbreaks,
    yunit = yunit,
    main = main,
    xlab = xlab,
    ylab = ylab,
    col = col,
    type = type,
    draw0 = draw0,
    box = box,
    axes = axes,
    annotate = TRUE,
    ...
  )

})
